import { Button } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useSelector } from 'react-redux';
import { useDispatch } from 'react-redux';

import { selectcounter } from './store/ProductSlice';

import {increment,decrement} from './store/ProductSlice'


const counter: NextPage = (props: any) => {
    const selectcounters = useSelector(selectcounter) as any ;
    const dispatch = useDispatch() as any 
    return (
      <div className="container">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className="row">
          <h1 className="text-center">

          </h1>
          <Button onClick={() => dispatch(increment())}>Increment</Button>
          <Button onClick={() => dispatch(decrement())}>decrement</Button>
          <p>
            Go to <Link href="/">
              <a>Home</a>
            </Link> {' | '}
            <Link href="/product">
              <a>Product</a>
            </Link>
          </p>
  
          <p>
            Hello, {props.profileData}!
          </p>
  
        </main>
      </div>
    );
  };






  export default counter